name: Pull Docker Image and Upload（adguardhome）

on:
  workflow_dispatch:

jobs:
  pull-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python Docker SDK
      run: pip install docker

    - name: Pull Docker image using Python
      run: python pull_image_adguardhome.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add adguardhome.tar
        git diff --quiet && git diff --staged --quiet || git commit -m "Update rules: $(date +'%Y-%m-%d %H:%M UTC+8')"
        git push
